spring.application.name=eletrojun_project
# Configurações MQTT e de Alertas (API-001 e ALERTA-001)
app.mqtt.broker=${MQTT_BROKER_URL:tcp://broker.hivemq.com:1883}
app.mqtt.sensor-topic=${MQTT_SENSOR_TOPIC:esp32_Eletrojun_Dht11/sensor}
app.mqtt.mode-topic=${MQTT_MODE_TOPIC:esp32_Eletrojun_Dht11/modo}
